# Generated by Django 5.1.4 on 2026-06-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnfenSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('inactive', 'No Activo'), ('watch', 'Vigilancia de El Niño Costero'), ('alert', 'Alerta de El Niño Costero')], default='inactive', max_length=20)),
                ('raw_text', models.TextField(default='')),
                ('summary', models.TextField()),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enfen_summaries',
                'ordering': ['-date'],
            },
        ),
    ]
