# Generated by Django 5.1.4 on 2026-06-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfensummary',
            name='bulletin_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enfensummary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enfensummary',
            name='source_url',
            field=models.URLField(default=''),
        ),
    ]
