# Generated by Django 5.1.4 on 2026-06-26 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('ubigeo_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(db_index=True, default='', max_length=100)),
                ('count', models.IntegerField(db_index=True, default=0)),
                ('level', models.CharField(choices=[('no_record', 'No Record'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='no_record', max_length=20)),
                ('years', models.JSONField(default=list)),
                ('geom', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('no_record', 'No Record'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'checklist_items',
                'ordering': ['level', 'order'],
                'unique_together': {('level', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinpad_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('phenomenon', models.CharField(max_length=200)),
                ('displaced', models.IntegerField(default=0)),
                ('affected', models.IntegerField(default=0)),
                ('victims', models.IntegerField(default=0)),
                ('destroyed_homes', models.IntegerField(default=0)),
                ('damaged_homes', models.IntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to='districts.district')),
            ],
            options={
                'db_table': 'emergencies',
                'ordering': ['-year', '-date'],
            },
        ),
    ]
