# Generated by Django 5.1.4 on 2026-06-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='text',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='emoji',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
