# Generated by Django 5.1.4 on 2026-06-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0002_remove_checklistitem_text_checklistitem_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='sinpad_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
